### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by yanksx233** [SHI-Labs/NATTEN#13]
When I run following code
```python
import torch
from natten import NeighborhoodAttention2D

device = torch.device("cuda:5")
na2d = NeighborhoodAttention2D(dim=128, kernel_size=7, dilation=2, num_heads=4).to(device)
x = torch.rand((1, 64, 64, 128)).to(device)
y = na2d(x)
```

But OOM:
```shell
attn = attn.softmax(dim=-1)
RuntimeError: CUDA error: out of memory
```

Here is response of `nvidia-smi`:

```shell
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:1A:00.0 Off |                  N/A |
| 78%   68C    P2   321W / 350W |  23294MiB / 24268MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:1B:00.0 Off |                  N/A |
|100%   81C    P2   326W / 350W |   8768MiB / 24268MiB |     65%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  On   | 00000000:1C:00.0 Off |                  N/A |
| 90%   74C    P2   311W / 350W |  21104MiB / 24268MiB |     73%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce ...  On   | 00000000:1D:00.0 Off |                  N/A |
|100%   80C    P2   324W / 350W |  21104MiB / 24268MiB |     73%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA GeForce ...  On   | 00000000:1E:00.0 Off |                  N/A |
| 94%   76C    P2   318W / 350W |  21104MiB / 24268MiB |     98%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA GeForce ...  On   | 00000000:3D:00.0 Off |                  N/A |
| 31%   39C    P8    22W / 350W |      3MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA GeForce ...  On   | 00000000:3F:00.0 Off |                  N/A |
| 90%   73C    P2   318W / 350W |  21104MiB / 24268MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA GeForce ...  On   | 00000000:40:00.0 Off |                  N/A |
| 87%   74C    P2   316W / 350W |  21104MiB / 24268MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   8  NVIDIA GeForce ...  On   | 00000000:41:00.0 Off |                  N/A |
| 82%   71C    P2   314W / 350W |  11930MiB / 24268MiB |     60%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by yanksx233** [comment]
But strangely, I'm training model with `NeighborhoodAttention`, it's work. When I testing my model, it show `out of memory`, the training is running at this time.

**Comment by alihassanijr** [comment]
Hi,

That should not happen. Are you sure your SMI is configured correctly? SMI GPU IDs don't necessarily correspond to the cuda id. Can you confirm that, and make sure it's not a change you made?

I just tried it on a 2080 Ti with only 11 gigs of memory and it works just fine:
```
import torch
from natten import NeighborhoodAttention2D

device = torch.device("cuda:5")
na2d = NeighborhoodAttention2D(dim=128, kernel_size=7, dilation=2, num_heads=4).to(device)
x = torch.rand((1, 64, 64, 128)).to(device)
y = na2d(x)
```
After `x` is allocated:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.63.01    Driver Version: 470.63.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   5  NVIDIA GeForce ...  On   | 00000000:89:00.0 Off |                  N/A |
| 18%   31C    P2    49W / 250W |    662MiB / 11019MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    5   N/A  N/A    327991      C   python3                           659MiB |
+-----------------------------------------------------------------------------+
```
After `y = na2d(x)`:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.63.01    Driver Version: 470.63.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   5  NVIDIA GeForce ...  On   | 00000000:89:00.0 Off |                  N/A |
| 18%   32C    P2    49W / 250W |    682MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    5   N/A  N/A    327991      C   python3                           679MiB |
+-----------------------------------------------------------------------------+
```

**Comment by alihassanijr** [comment]
By the way, `to` is not a reliable way of limiting torch's CUDA ops to a single GPU.
Typically the `with torch.device(device):` wrapper or the set cuda device method are better choices.
`CUDA_VISIBLE_DEVICES` is a last resort, still better.

**Comment by yanksx233** [comment]
GPU 2,3,4,6,7 is my training process with DDP, it's works just fine.

**Comment by alihassanijr** [comment]
When I ran the snippet you sent I noticed torch reserves memory on GPU 0 as well. Not sure why, but not too surprising either. Can you try adding `torch.cuda.set_device(device)` or doing `CUDA_VISIBLE_DEVICES=5 python3` and trying it?

**Comment by yanksx233** [comment]
when I use `to.(device)`, only `fc` ok

**Comment by yanksx233** [comment]
I run `CUDA_VISIBLE_DEVICES=5 python3 demo.py`, and set `device = torch.device("cuda:0")`. It's ok both for `fc` and `na`.

**Comment by alihassanijr** [comment]
So what's (most likely) happening is that when you don't set the torch cuda device, the API call to the cuda backend reserves memory on cuda:0. I'm not sure why that's happening, but after thoroughly testing it, that appears to be the issue.
The only tensors that our kernels reserve are on the same device (I specifically checked that it is true just now).
And I tested the call to make sure it's not something like the autograd function.

The only temporary fix I can think of is adding the device wrapper -- which is not a solution I like, because it only fixes the issue, and doesn't explain it.

**Comment by yanksx233** [comment]
Thank very much for your reply. In any case, this is a very very great work. It prefectly introduces inductive bias of convolution to self-attention.

**Comment by alihassanijr** [comment]
Thank you very much for your comment; glad you find it useful.

As far as this issue goes, I'll mark this as a bug so we resolve it in a future release.
It is probably because we're creating the output tensors within our CPP interface, and that for some reason reserves memory on the default CUDA device (cuda:0).
We'll test taking that part out and if it doesn't result in a performance hit, we'll merge, and if it does, we'll figure something else out.
